#needs to update
image: gitlab-registry.cern.ch/atlas-tdaq-felix/gitlab_ci_runner:cc7-netboot-dev

variables:
  PROJECT_NAME: felix-monitoring
  GIT_SUBMODULE_STRATEGY: normal
  GIT_DEPTH: 0

default:
  tags:
    - atlas-tdaq-felix
    - cvmfs
    - cmem
    - infiniband
    - pc-tbed-felix-02.cern.ch

stages:
- config-build-test

.config-build-test: &config-build-test
  stage: config-build-test
  script:
  - cd ${CI_PROJECT_DIR}
  - source cmake_tdaq/bin/setup.sh
  - cmake_config
  - cd ${BINARY_TAG}
  - make -j 4
  - ctest --output-on-failure -R felixcore

build:40:
  <<: [ *config-build-test ]
  variables:
    REGMAP_VERSION: "0x0400"

build:50:
  <<: [ *config-build-test ]
  variables:
    REGMAP_VERSION: "0x0500"

